version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - exhibition_network
    

  # redis-commander:  # Redis 管理界面，可选
  #   image: rediscommander/redis-commander:latest
  #   environment:
  #     - REDIS_HOSTS=local:redis:6379
  #   ports:
  #     - "8081:8081"
  #   networks:
  #     - exhibition_network
  #   depends_on:
  #     - redis


  rq-worker:
    build: .
    command: rq worker exhibition
    environment:
      # - DATABASE_URL=http://host.docker.internal:8000/api/data
      - DATABASE_URL=http://172.18.0.1:8000/api/data # Used for Linux deployment
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - MONGODB_HOST=mongodb://172.18.0.1:27017/
      - MONGODB_DB=SeeM
    env_file:
      - .env
    volumes:
      - ./data/index_files:/app/data/index_files
    depends_on:
      - redis
    networks:
      - exhibition_network

  api:
    build: .
    ports:
      # - "5000:8000"
      - "5001:5001" # Used for Linux deployment
    environment:
      # - DATABASE_URL=http://host.docker.internal:8000/api/data
      - DATABASE_URL=http://172.18.0.1:8000/api/data # Used for Linux deployment
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - MONGODB_HOST=mongodb://172.18.0.1:27017/
      - MONGODB_DB=SeeM
    env_file:
      - .env
    volumes:
      - ./data/index_files:/app/data/index_files
    depends_on:
      - redis
      - rq-worker
    networks:
      - exhibition_network

volumes:
  redis_data:

networks:
  exhibition_network:
    external: true